create table team
(
    id int generated by default as identity primary key,
    name varchar(50) not null
);

create table category
(
    id int generated by default as identity primary key,
    name varchar(50) not null
);

create table person
(
    id int generated by default as identity primary key,
    team_id int references team (id) on delete set null,
    full_name varchar(50) not null,
    email varchar(50) not null unique,
    password varchar(100) not null,
    balance float not null check (balance >= 0),
    gender varchar(1) not null check (gender IN ('F', 'M'))
);

create table category_transaction
(
    id int generated by default as identity primary key,
    person_id int references person (id) on delete cascade,
    category_id int references category (id) on delete set null,
    amount float not null,
    created_at timestamp not null CHECK (created_at > TIMESTAMP '2023-01-01 00:00:00')
);

create table person_transaction
(
    id int generated by default as identity primary key,
    person_from_id int references person (id) on delete set null,
    person_to_id int references person (id) on delete set null,
    amount float not null check (amount > 0),
    created_at timestamp not null CHECK (created_at > TIMESTAMP '2023-01-01 00:00:00'),
    check (person_from_id <> person_to_id)
);

create table invitation
(
    id int generated by default as identity primary key,
    person_from_id int references person (id) on delete cascade,
    person_to_id int references person (id) on delete cascade,
    check (person_from_id <> person_to_id),
    unique (person_from_id, person_to_id)
);